### ISSUE TITLE
PA Review: Provide task details

### ISSUE THREAD

**Issue by brillantewang** [brillantewang/taskwombat#6]

**Comment by LochandQuay** [comment]
@brillantewang 

- [ ] On the form, after I click save and the field shrinks and moves to the next, I'd like to see the information I entered displayed in that smaller box. 
- [ ] Are you trying to save to the database every time you click the save button? It's giving you a ton of 422's.
- [ ] I'd like to see some way to cancel the form (probably just a cancel button somewhere that redirects to the dashboard).

Otherwise this is beautiful.

**Comment by brillantewang** [comment]
1. Was meaning to do this but found it a bit tricky trying to get it to render text conditionally if the element had class 'hidden', since it would try to getElementById before the DOM was even ready and would error out, if that makes sense. Would love to come back to this later if I have time.
2. I intentionally designed it to save to the database everytime we hit save so it can bring back error messages from rails in order to display them on the form. I couldn't think of another way at the time to get the error messages but I realize this is probably super hacky.
3. Can add that real quick. 

Thank you!

**Comment by LochandQuay** [comment]
@brillantewang 

I think you should remove the database saving on each save--the form broke after I clicked on the address save button: `Uncaught TypeError: this.props.errors.filter is not a function`. I also got an internal server error.

**Comment by brillantewang** [comment]
It's because I didnt' push my database to heroku again after renaming a column, it should be fixed now.

Also I added the navbar to the task form so that you can click the logo to redirect to the dashboard.
